### ISSUE TITLE
Some code snippets are not appearing

### ISSUE THREAD

**Issue by jaydson** [ender-js/website#9]
Examples:
"You can then install Ender with the following single line: "
There's no single line :(

"A completed package file might look something like this: "
There's no code bellow

**Comment by rvagg** [comment]
Thanks for picking this up @jaydson! Turns out it's related child_process 'exit' and 'close' events, strangely enough. Works for me locally but works different on a slower, SmartOS machine where ender.jit.su is hosted.

Fixed now I think ([details here](https://github.com/rvagg/node-pygmentize-bundled/commit/d1be63c9ece41d4357f7dfc5e83aa386c50e7605)).

**Comment by luk-** [comment]
Wow good find. I checked it out locally and didn't see an issue in the short time I looked.

**Comment by rvagg** [comment]
_bug fixing by hunch_; we've all been there

**Comment by jaydson** [comment]
Great.
Apparently, everything is working now.

On Thu, Dec 13, 2012 at 9:43 PM, Rod Vagg notifications@github.com wrote:

> _bug fixing by hunch_; we've all been there
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ender-js/website/issues/9#issuecomment-11359041.

## 

Jaydson Gomes
JavaScript Programmer
@jaydson http://twitter.com/jaydson
http://jaydson.org
 http://twitter.com/jaydson
LinuxUser #509003
